CREATE TABLE PT_POLIZA(CD_POLIZA INT PRIMARY KEY AUTO_INCREMENT, 
DS_NUMERO VARCHAR(100) NOT NULL, NM_VALOR_POLIZA INT NOT NULL);

CREATE TABLE PT_VEHICULO(CD_VEHICULO INT PRIMARY KEY AUTO_INCREMENT, 
DS_PLACA VARCHAR(20) NOT NULL,
DS_MODELO VARCHAR(20) NOT NULL, 
DS_MARCA VARCHAR(20) NOT NULL, 
NM_CANTIDAD_PASAJEROS INT NOT NULL,
CD_POLIZA INT NOT NULL, FOREIGN KEY(CD_POLIZA) REFERENCES PT_POLIZA(CD_POLIZA));

CREATE TABLE PT_ASEGURADO(CD_ASEGURADO INT PRIMARY KEY AUTO_INCREMENT, 
NM_DOCUMENTO VARCHAR(50) NOT NULL, 
NM_SALARIO INT NOT NULL, 
NM_CREDITOS INT NOT NULL, 
NM_GASTOS_FIJOS INT NOT NULL, 
CD_POLIZA INT NOT NULL, FOREIGN KEY(CD_POLIZA) REFERENCES PT_POLIZA(CD_POLIZA));

CREATE TABLE PT_AFILIACION(CD_AFILIACION INT PRIMARY KEY AUTO_INCREMENT,
CD_VEHICULO INT NOT NULL REFERENCES PT_VEHICULO(CD_VEHICULO),
CD_POLIZA INT NOT NULL, FOREIGN KEY(CD_POLIZA) REFERENCES PT_POLIZA(CD_POLIZA),
CD_ASEGURADO INT NOT NULL,FOREIGN KEY(CD_ASEGURADO) REFERENCES PT_ASEGURADO(CD_ASEGURADO));
